dist: trusty
sudo: false
language: node_js
node_js:
- '8'
addons:
  chrome: stable
cache: yarn
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn global add greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
script: yarn test
after_script:
- greenkeeper-lockfile-upload
